 gui:
  namespace_id: "crafting"
  texture_offset: -8
  inv_size: 54
  title: "&8Recipe Book"
  title_offset: 16
  left_arrow:
    slot: 0
    texture: "oraxen:left_arrow"
  right_arrow:
    slot: 8
    texture: "oraxen:right_arrow"
  close_button:
    slot: 4
    texture: "BARRIER"
