name: ShowMeMyRecipes
version: '${version}'
main: me.wuzzyxy.showmemyrecipes.ShowMeMyRecipes
api-version: '1.19'

depend:
  - 'Oraxen'

commands:
  recipes:
    description: Show the recipes for the item in your hand
    usage: /recipes
